name: Build and Deploy

on:
  push:
    branches: [SPS-058_support-arm64]

  workflow_dispatch:
    inputs:
      version_number:
        required: true
        type: string
        description: Version number to deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Determine Version
        run: |
          if [ ! -z "${{ github.event.inputs.version_number }}" ]; then
            echo "UNBOUND_VERSION=${{ github.event.inputs.version_number }}" >> $GITHUB_ENV
          else
            echo "UNBOUND_VERSION=$(find * -type d -regex "[0-9]+\.[0-9]+\.[0-9]+" | sort --version-sort | tail -n 1)" >> $GITHUB_ENV
          fi

          echo "REGISTRY_TITLE=$(echo ${{ secrets.DOCKERHUB_USERNAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_TITLE }}/unbound
          tags: |
            ${{ env.REGISTRY_TITLE }}/unbound:latest
            ${{ env.REGISTRY_TITLE }}/unbound:${{ env.UNBOUND_VERSION }}

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.UNBOUND_VERSION }}
          platforms: linux/amd6,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
